module.exports = {
    eightBall: [
        "As I see it, yes",
        "Ask again later",
        "Better not tell you now",
        "Cannot predict now",
        "Concentrate and ask again",
        "Don’t count on it",
        "It is certain",
        "It is decidedly so",
        "Most likely",
        "My reply is no",
        "My sources say no",
        "Outlook not so good",
        "Outlook good",
        "Reply hazy, try again",
        "Signs point to yes",
        "Very doubtful",
        "Without a doubt",
        "Yes",
        "Yes – definitely",
        "You may rely on it"
    ],
    truth: [
        "When was the last time you lied?",
        "When was the last time you cried?",
        "What's your biggest fear?",
        "What's your biggest fantasy?",
        "Do you have any fetishes?",
        "What's something you're glad your mum doesn't know about you?",
        "Have you ever cheated on someone?",
        "What's the worst thing you've ever done?",
        "What's a secret you've never told anyone?",
        "Do you have a hidden talent?",
        "Who was your first celebrity crush?",
        "What are your thoughts on polyamory?",
        "What's the worst intimate experience you've ever had?",
        "Have you ever cheated in an exam?",
        "What's the most drunk you've ever been?",
        "Have you ever broken the law?",
        "What's the most embarrassing thing you've ever done?",
        "What's your biggest insecurity?",
        "Have you ever stayed friends with someone because it benefitted you beyond just the friendship?",
        "What's the biggest mistake you've ever made?",
        "What's the most disgusting thing you've ever done?",
        "Who would you like to kiss in this room?",
        "What's the worst thing anyone's ever done to you?",
        "Have you ever had a run in with the law?",
        "What's your worst habit?",
        "What's the worst thing you've ever said to anyone?",
        "Have you ever peed in the shower?",
        "What's the strangest dream you've had?",
        "Have you ever been caught doing something you shouldn't have?",
        "What's the worst date you've been on?",
        "What's your biggest regret?",
        "What's the biggest misconception about you?",
        "Have you ever said something you regret about someone in this room?",
        "What's one thing you wish people knew about you?",
        "Why did your last relationship break down?",
        "What's the most trouble you've been in?",
        "What's the worst thing you've ever lied about?",
        "What's the best piece of advice you've ever been given?",
        "What's your guilty pleasure?",
        "What's one thing you only do when you're alone?",
        "If you had to get back with an ex, who would you choose?",
        "If you had to cut one friend out of your life, who would it be?",
        "Do you have a favourite friend?",
        "Who is your best friend?",
        "Which is your favourite food?",
        "What are your top three turn-ons?",
        "What is your deepest darkest fear?",
        "Who is your crush?",
        "What was the last thing you searched for on your phone?",
        "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
        "Have you ever walked in on your parents doing it?",
        "After you've dropped a piece of food, what's the longest time you've left it on the ground and then ate it?",
        "Have you ever tasted a booger?",
        "What's the first thing you would do if you woke up one day as the opposite sex?",
        "Have you ever peed in the pool?",
        "Have you ever farted in an elevator?",
        "Of the people in this room, who do you want to trade lives with?",
        "What are some things you think about when sitting on the toilet?",
        "Did you have an imaginary friend growing up?",
        "Do you cover your eyes during a scary part in a movie?",
        "Have you ever practiced kissing in a mirror?",
        "Did your parents ever give you the “birds and the bees” talk?",
        "What is your worst habit?",
        "Have you ever had a wardrobe malfunction?",
        "What is your biggest fear in a relationship?",
        "What was your funniest first date ever?",
        "What is your biggest turn off in a partner?",
        "What is your weirdest habit?",
        "How many kids would you like to have?",
        "What is the perfect first day?",
        "What is one embarrassing fact I should know about you?",
        "What was your childhood nickname?",
        "What is your favourite movie?",
        "Describe your worst date ever?",
        "If there was no such thing as money, what would you do with your life?",
        "What is your favourite food?",
        "What are your three favourite colours, and why?",
        "What is your dream job?",
        "If you were trapped on an island for 3 days, what would you take with you?",
        "Who is your favourite person and why?",
        "Do you prefer apple or android?",
        "How do you put your toilet paper on the roll?",
        "What is your best talent?",
        "Do you believe in love at first sight?",
        "Do you believe in love at all?",
        "What is your dream wedding?",
        "Would you ever consider being a nudist?",
        "How do you feel about end pieces of a loaf of bread?",
        "Can you touch your tongue to your nose?",
        "If you could take away one bad thing in the world, what would it be?",
        "What is the most exotic food that you have ever eaten?",
        "What country would like to live in if you had the chance?",
        "If you could change one thing on your body, what would it be?",
        "What do you daydream about the most?",
        "Describe the weirdest dream you've ever had?",
        "Is the dress Black and Blue or Gold and White?",
        "How do you feel about social media?",
        "What is your favourite season of the year?",
        "Could you go a week without junk food?",
        "How was your first kiss?",
        "Describe your worst kiss ever?",
        "Do you like to exercise?",
        "Have you ever blacked out from drinking too much?",
        "Did you smoke or drink before college? Or did you start when you got here?",
        "What is the craziest thing that you have ever done while drunk?",
        "What is the funniest dream that you have ever had?",
        "Who is your best looking teacher that you have ever had?",
        "Have you ever cheated on any test?",
        "Who is your crush at school?",
        "Who is the most annoying person you know?",
        "Have you ever pulled a prank on your teacher?",
        "Have you ever lied to your parents about what you were doing after school?",
        "Have you ever blamed something that you have done on one of your siblings?",
        "What college do you plan on going to?",
        "Are you still a virgin?",
        "How many boyfriends (or girlfriends) have you had?",
        "Have you ever been kissed yet? If so, who was your best kiss?",
        "What is your biggest pet peeve?",
        "What is the best vacation you've ever been on?",
        "Have you ever told one of your best friend's secrets, even if you said you wouldn't?",
        "Have you ever had a crush on someone that your best friend has dated?",
        "What is the most annoying thing that one of your siblings has done?",
        "Do you have a job? If so, what is your favourite thing about it?",
        "If you were a billionaire, what would you spend your time doing?",
        "What is the longest time you have ever been grounded?",
        "What is the longest time that you think you could go without your cell phone?",
        "What is the most expensive thing you own?",
        "If you had the choice to live on your own right now, would you do it?",
        "Can you see yourself being married to the creepiest kid a your school someday?",
        "Would you ever get on a dating website?",
        "Have you ever watched an adult film without your parents knowing?",
        "If you could own your own business one day, what would it be?",
        "What is your favourite kind of clothing?",
        "What celebrity are you obsessed with?",
        "What is the funniest youtube video you have ever seen?",
        "Who is the worst teacher you have ever had, why?",
        "What is your favourite sports team?",
        "How old were you when you had your first kiss?",
        "How long have you gone without showering?",
        "What color is your underwear?",
        "What is your special talent?",
        "What's your ex-girlfriend/boyfriend name?",
        "What is the most embarrassing moment of your life?",
        "What would you do with a million dollars if you ever won the lottery?",
        "If you could change one thing on your body, what would it be?",
        "What is the silliest thing you have an emotional attachment to?",
        "What was your childhood nickname?",
        "What is something you have stolen?",
        "Say 5 bad habits you have?",
        "Tell 5 secrets of yours?",
        "What is the most embarrassing thing your parents have caught you doing?",
        "Have you ever peed in the swimming pool?",
        "If you could marry one teacher in the school, who would you pick and why?",
        "Have you ever lied to your best friend?",
        "What he craziest thing that you have ever done without your parents knowing?",
        "What would you do if your parents left the house to you for a whole week?",
        "What is your favourite song that is out right now?",
        "Could you go two months without talking to your friends?"
    ],
    dare: [
        "Show the most embarrassing photo on your phone",
        "Show the last five people you texted and what the messages said",
        "Let the rest of the group DM someone from your Instagram account",
        "Eat a raw piece of garlic",
        "Do 100 squats",
        "Show us your screen time report",
        "Keep three ice cubes in your mouth until they melt",
        "Say something dirty to the person on your left",
        "Give a foot massage to the person on your right",
        "Put 10 different available liquids into a cup and drink it",
        "Yell out the first word that comes to your mind",
        "Give a lap dance to someone of your choice",
        "Remove four items of clothing",
        "Like the first 15 posts on your Facebook newsfeed",
        "Eat a spoonful of mustard",
        "Keep your eyes closed until it's your go again",
        "Seductively eat a banana",
        "Empty out your wallet/purse and show everyone what's inside",
        "Pretend to be the person to your right for 10 minutes",
        "Eat a snack without using your hands",
        "Say two honest things about everyone else in the group",
        "Try and make the group laugh as quickly as possible",
        "Try to put your whole fist in your mouth",
        "Tell everyone an embarrassing story about yourself",
        "Try to lick your elbow",
        "Post the oldest selfie on your phone on Instagram Stories",
        "Tell the saddest story you know",
        "Howl like a wolf for two minutes",
        "Dance without music for two minutes",
        "Pole dance with an imaginary pole",
        "Let someone else tickle you and try not to laugh",
        "Put as many snacks into your mouth at once as you can",
        "Scroll through your phone book until someone says stop. You either have to call or delete that person",
        "Down your drink (responsibly)",
        "Try and make yourself cry in front of the group",
        "Tell the group two truths and a lie, and they have to guess which one the lie is",
        "Show off your secret talent",
        "Reply to the first five Instagram Stories on your timeline",
        "Share the first celebrity on your timeline's Instagram to your Story",
        "Put on as many layers as possible in 60 seconds",
        "Fill your mouth with drink and gargle your answer to the next Truth",
        "Smile as widely as you can and hold it for two minutes",
        "Tell me about your first kiss.",
        "Do an impression of your favorite celebrity",
        "Close your eyes and send a blind text to a random person",
        "Go grab a broom and do your best tango",
        "Give a 3 minute stand-up comedy routine",
        "Break dance",
        "Make up a story about the item to your right",
        "Sing the alphabet without moving your mouth",
        "Do your best president impression",
        "Yell out the first word that comes to your mind right now",
        "Call the pizza place and order 300 sardine pizzas",
        "Pound on your chest and act like a gorilla for the next minute",
        "Sing everything you say for the next 10 minutes",
        "Give a foot massage",
        "Say the alphabet backwards in 15 seconds",
        "Go to the neighbour's house and ask for a banana",
        "Go up to someone random and ask for a hug",
        "Set your cell phone language to Chinese for the next 10 minutes",
        "Act like your favourite Disney character for the rest of the game",
        "Sing 'Twinkle Twinkle, Little Star' while beat boxing",
        "Give a concert with your air guitar",
        "Make a poem using the words orange and moose",
        "Unbuckle your own belt using your elbows",
        "Brush someone else's teeth",
        "Belly dance to a country song",
        "Make up a country song of the top of your head",
        "Get on all fours and act like a dog until your next turn",
        "Make up a short rap about another player",
        "Act like Romeo from 'Romeo and Juliet' (pick who you want to be Juliet)",
        "Do an impression of someone until another player can guess who you are",
        "Say 'ya heard meh' after everything you say for the next 5 minutes",
        "Act like you do not understand your own language until your next turn (come up with your own language)",
        "Use the letters of the name of another player to describe them",
        "Only use sign language for the next round",
        "Do pushups until it's your turn again",
        "Wear a finger moustache for the next 5 minutes",
        "Only use your elbows and knees to go make a sandwich",
        "Write a Facebook (or other social media) post only using your toes",
        "Take a selfie with the toilet and post it online",
        "Paint your toenails only using your teeth",
        "Brush your spouse's teeth",
        "Prank call someone you know.",
        "Ask the neighbors to borrow a cup of sugar.",
        "Post a YouTube video of you singing a currently popular song.",
        "Go outside and shout at the top of your lungs,\"I am [your name]! Hear me roar!\"",
        "Moonwalk while a friend takes a video.",
        "Paint each toenail and fingernail a different color and keep the polish on for a week.",
        "In your next class, raise your hand each time the teacher asks a question and give the answer (if you can!!)",
        "Do the silliest dance that you can think of",
        "Call someone random, and talk freaky to them",
        "Email one of your professors and tell them you love them",
        "Lick the wall",
        "Exchange shirts with the person next to you",
        "Try licking your elbow.",
        "Give a lip kiss to someone near you and sent a screenshot",
        "Crack an egg on your head.",
        "Call your parents and tell them you're dropping out",
        "Record yourself doing the silliest dance you can do, and post it to Facebook",
        "Ask your crush out on a date",
        "Put the socks of the person to your right in your mouth",
        "Take a selfie with your finger up your nose and post it to all your social media",
        "Lick a car tire."
    ]
}